### ISSUE TITLE
cassandra-stress failing with `NullPointerException` on call to `Connection.shardId()` 

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#180] opened 2022-11-30 10:12 UTC
Recently we started working with latest cassandra-stress from scylla master,

and we keep run into a few cases the stress was broken in the middle like the following:

Stress is failing with unclear reason (return code 1)
```
2022-11-29 16:19:50.968: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=74718019-b5df-4f33-a186-b0647e4bdacd during_nemesis=NoCorruptRepair duration=3h10m0s: node=Node longevity-10gb-3h-master-loader-node-54aa0b5e-eastus-1 [20.172.155.136 | 10.0.0.11] (seed: False)
stress_cmd=cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
errors:
Stress command completed with bad status 1: WARN  13:09:52,113 Not using advanced port-based shard awareness with /10.0.0.8:9042 because we're m
```

Seems like hours before there was a failures like that: (full logs can be found in the load-set file below)
```
SEVERE: RuntimeException while executing runnable com.datastax.driver.core.HostConnectionPool$5@3fab789d with executor com.google.common.util.concurrent.MoreExecutors$DirectExecutorService@35dec07b
java.lang.NullPointerException
	at com.datastax.driver.core.Connection.shardId(Connection.java:1050)
total,     138391216,   67702,   67702,   67702,    14.8,     9.7,    44.7,    76.6,   124.9,   183.4, 2145.0,  0.00210,      0,      0,       0,       0,       0,       0
	at com.datastax.driver.core.HostConnectionPool$5.run(HostConnectionPool.java:1017)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.access$3700(Connection.java:1718)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture$1.operationComplete(Connection.java:1748)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture$1.operationComplete(Connection.java:1741)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
total,     138722694,   66296,   66296,   66296,    15.1,     8.8,    50.0,    94.1,   181.5,   273.4, 2150.0,  0.00210,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at com.datastax.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at com.datastax.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1740)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1718)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1657)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1648)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
total,     139051640,   65789,   65789,   65789,    15.1,     8.1,    52.8,    95.8,   168.2,   248.5, 2155.0,  0.00210,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at com.datastax.shaded.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at com.datastax.shaded.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1164)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:755)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
total,     139372669,   64206,   64206,   64206,    15.6,     8.1,    55.2,   109.8,   180.7,   246.2, 2160.0,  0.00209,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at com.datastax.shaded.netty.channel.AbstractChannel.close(AbstractChannel.java:244)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1739)
	at com.datastax.driver.core.Connection.tryTerminate(Connection.java:1144)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1567)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1477)
	at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
total,     139705126,   66491,   66491,   66491,    15.0,     9.4,    47.0,    83.1,   125.2,   200.5, 2165.0,  0.00209,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
total,     140030550,   65085,   65085,   65085,    15.3,     8.6,    53.1,    90.4,   146.9,   199.4, 2170.0,  0.00208,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
total,     140357279,   65346,   65346,   65346,    15.3,     9.9,    47.7,    86.6,   138.5,   210.8, 2175.0,  0.00208,      0,      0,       0,       0,       0,       0
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

according to the timestamps, it was while this nemesis run:

disrupt_grow_shrink_cluster | longevity-10gb-3h-master-db-node-54aa0b5e-eastus-2 | Succeeded | 2022-11-29 13:33:09 | 2022-11-29 13:50:07
-- | -- | -- | -- | --

it's scaling the cluster by 1 node, the decommissioning that node,  so this probably caused by some topology change...

## Installation details

Kernel Version: 5.15.0-1023-azure
Scylla version (or git commit hash): `5.2.0~dev-20221129.8bc0af9e34fa` with build-id `64a68bc4306bd55bc726a81b066ae3350e79d108`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-8 (23.96.49.29 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-7 (52.152.233.218 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-6 (172.173.160.18 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-5 (20.231.122.14 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-4 (20.172.155.115 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-3 (4.246.181.200 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-2 (4.246.181.198 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-54aa0b5e-eastus-1 (20.172.155.182 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-11-29T13-26-23` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f8224bdc2a2c0d512fbe00b7b4870591c5d3414a/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=54aa0b5e-c3a5-4bcb-b657-6b83d804a11d)
- Show all stored logs command: `$ hydra investigate show-logs 54aa0b5e-c3a5-4bcb-b657-6b83d804a11d`

## Logs:
- **db-cluster-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/db-cluster-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/db-cluster-54aa0b5e.tar.gz)
- **monitor-set-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/monitor-set-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/monitor-set-54aa0b5e.tar.gz)
- **loader-set-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/loader-set-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/loader-set-54aa0b5e.tar.gz)
- **sct-runner-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/sct-runner-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/sct-runner-54aa0b5e.tar.gz)
- **parallel-timelines-report-54aa0b5e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/parallel-timelines-report-54aa0b5e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/54aa0b5e-c3a5-4bcb-b657-6b83d804a11d/20221129_165430/parallel-timelines-report-54aa0b5e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/131/)

**Comment by fruch** [comment] 2022-12-04 12:38
@avelanarius 

a guess, maybe it got todo with two node having the same ip adress 10.0.0.14 (not at the same time, but still they might be still in the hosts list of the driver, as the same time)

**Comment by roydahan** [comment] 2022-12-29 12:05
@aleksbykov I think this is the issue you saw in the weekend longevity.

**Comment by aleksbykov** [comment] 2022-12-29 12:07
@roydahan , yes. you right. It is exactly what happened during job

**Comment by mykaul** [comment] 2023-01-08 12:10
@Bouncheck , @avelanarius - any progress?

**Comment by Bouncheck** [comment] 2023-01-09 12:20
I'm on it and I have a workaround in mind but I'm trying to figure out how to properly reproduce this and test on my machine.

**Comment by DoronArazii** [comment] 2023-02-14 15:20
@Bouncheck what's the next steps here?

**Comment by Bouncheck** [comment] 2023-02-17 13:04
I think this will be merged once it passes driver CI tests, which right now fail due to other unrelated changes. But we're getting closer to fixing it.

**Closed as completed** 2023-02-20 12:13 UTC
Labels: bug

**Comment by mykaul** [comment] 2023-02-22 12:08
@avelanarius - it's (yet another?) reason to have a new Java driver release.

**Comment by avelanarius** [comment] 2023-02-22 12:10
OK, will release it in the coming few days.

**Comment by fruch** [comment] 2023-07-02 10:14
@avelanarius 
few days has passed, and we are still hitting this issue in while testing 2023.1

3.11.2.4 is the version used in both master and 5.2/2023.1, and we are missing this fix...
