### ISSUE TITLE
Unexpected error when using .withLocalDatacenter("DC_1")  while having single DC

### ISSUE THREAD

**Issue by amihayday** [scylladb/java-driver#64] opened 2021-01-31 12:01 UTC
failing with Error specifying there is a use of a different DC while running on a single DC. 

Driver version 4.x

receiving the following error:
[6:20 PM] OptionalLocalDcHelper [xxxxxx] [xx|default] You specified DC_1 as the local DC, but some contact points are from a different DC: Node(endPoint=x.x.x.x:9042, hostId=null, hashCode=xxxxxx)=null, Node(endPoint=x.x.x.x:9042, hostId=null, hashCode=xxxxx)=null; please provide the correct local DC, or check your contact points
2021-01-31 18:08:27,051 WARN c.d.o.d.i.c.p.ChannelPool [xx-xxx] [xx|x.x.x.x:9042] Error while opening new channel (ConnectionInitException: [xx|connecting...] Protocol initialization request, step 1 (OPTIONS): failed to send request (java.nio.channels.NotYetConnectedException))
2021-01-31 18:08:27,134 WARN c.d.o.d.i.c.p.ChannelPool [xx-xxx] [xx|/x.x.x.x:9042] Error while opening new channel (ConnectionInitException: [xx|connecting...] Protocol initialization request, step 1 (OPTIONS): failed to send request (java.nio.channels.NotYetConnectedException))

**Comment by tarzanek** [comment] 2021-01-31 12:46
4.9 was supposed to have it fixed: 
https://datastax-oss.atlassian.net/browse/JAVA-2835

so this should be retested and rechecked and ev. fixed again

**Comment by tarzanek** [comment] 2021-01-31 12:48
it might be an incompatibility between new 4.x drivers (and how they approach configs using profiles)
and old 3.x drivers  and scylla,  FYI @haaawk

**Comment by haaawk** [comment] 2021-02-01 03:19
Thanks Lubos. Could you please comment on the github issue? Thanks.

**Comment by tarzanek** [comment] 2021-02-02 12:59
I am debugging this now
@haaawk it seems it is connected with fact that AWS uses external IPs for cqlsh and internal IPs for internal communication

when we connect to the same cluster but change endpoints to internal ones it works

during debug I see not initialized datacenter for the check in
https://github.com/scylladb/java-driver/blob/4.9.0-scylla/core/src/main/java/com/datastax/oss/driver/internal/core/loadbalancing/helper/OptionalLocalDcHelper.java#L95

node.getDatacenter() is null so it seems in above case the metadata is not populated properly

**Comment by tarzanek** [comment] 2021-02-02 13:02
fwiw I can replicate the same behaviour with datastax 4.x so this looks like some incompatibility in metadata coming from scylla ?

**Comment by tarzanek** [comment] 2021-02-03 14:15
right now it looks like we might have a fix for this in scylla metadata by setting https://github.com/scylladb/scylla/blob/master/db/config.cc#L436

listen_address: *privateIP*
broadcast_address: *privateIP*

but it should be per above *publicIP*  (or 0.0.0.0 to allow both interface access ? user wants to use both ifaces to connect, so I'd go with 0.0.0.0)

will verify

**Comment by tarzanek** [comment] 2021-02-03 14:22
or address translations need to be set up ... https://docs.datastax.com/en/developer/java-driver/4.10/manual/core/address_resolution/

**Comment by tarzanek** [comment] 2021-02-03 15:23
ok, it works with address translation, however I only now figure out this is by design
the cluster is created privately, so it shouldn't be accessed from outside, hence this bug doesn't apply and code in driver is behaving OK, closing

**Closed as completed by tarzanek** 2021-02-03 15:23 UTC
