### ISSUE TITLE
docs: Issue on page Java Driver for Scylla and Apache Cassandra®

### ISSUE THREAD

**Issue by pogzie** [scylladb/java-driver#322] opened 2024-08-09 07:36 UTC
I would like to report an issue on page https://java-driver.docs.scylladb.com/scylla-4.15.0.x/index

### Problem
Docs looks to be outdated. 

###  Suggest a fix
Listing the version tags in https://github.com/scylladb/java-driver it looks to be 4.18 is the latest. This section needs to be updated accordingly as this is also something a lot of customer are asking: driver compatibility during upgrades.

![Screenshot from 2024-08-09 15-34-47](https://github.com/user-attachments/assets/e77e0036-af89-402b-8179-4b38e265722e)

**Comment by Bouncheck** [comment] 2024-08-09 23:45
This is a valid concern, but closing as duplicate of #302

**Closed as not planned by Bouncheck** 2024-08-09 23:45 UTC
Labels: documentation
