### ISSUE TITLE
RackAwareRoundRobinPolicy still send out requests to other racks

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#255] opened 2023-11-05 09:13 UTC
I have use case with 6 nodes, and c-s is using `RackAwareRoundRobinPolicy` that targets only rack `1a`

and all stress commands are showing the following logs 
```
Connected to cluster: longevity-cdc-100gb-4h-rackawar-db-cluster-7f55814f, max pending requests per connection null, max connections per host 8
WARN  17:17:34,494 Some contact points don't match local rack. Local rack = 1a. Non-conforming contact points: /10.4.8.52:9042 (dc=eu-west, rack=1c),/10.4.6.128:9042 (dc=eu-west, rack=1b),/10.4.10.155:9042 (dc=eu-west, rack=1c),/10.4.6.92:9042 (dc=eu-west, rack=1b)
Datatacenter: eu-west; Host: /10.4.2.35; Rack: 1a
Datatacenter: eu-west; Host: /10.4.8.52; Rack: 1c
Datatacenter: eu-west; Host: /10.4.6.128; Rack: 1b
Datatacenter: eu-west; Host: /10.4.10.155; Rack: 1c
Datatacenter: eu-west; Host: /10.4.6.92; Rack: 1b
Datatacenter: eu-west; Host: /10.4.3.54; Rack: 1a
Created schema. Sleeping 6s for propagation.
```

I assume that regredless of which nodes are passed as contact points, the driver would still work base on the logic of  `RackAwareRoundRobinPolicy` and communicate only the relevant rack 

but other nodes in rack 1b, 1c, are getting requests

![image](https://github.com/scylladb/java-driver/assets/340979/ebb98b3b-ac99-4876-8289-96877b635d65)

## Installation details

Kernel Version: 5.15.0-1049-aws
Scylla version (or git commit hash): `5.5.0~dev-20231027.227136ddf54f` with build-id `420b5e5ef0c99c93991034185a1061ec90ab2c43`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-7 (3.249.58.125 | 10.4.10.54) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-6 (54.155.166.212 | 10.4.8.52) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-5 (34.240.100.209 | 10.4.10.155) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-4 (34.254.65.243 | 10.4.6.92) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-3 (54.72.53.223 | 10.4.6.128) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-2 (63.35.252.244 | 10.4.2.35) (shards: 14)
- longevity-cdc-100gb-4h-rackawar-db-node-7f55814f-1 (18.203.234.95 | 10.4.3.54) (shards: 14)

OS / Image: `ami-0445669e3c59c66ab` (aws: undefined_region)

Test: `longevity-cdc-100gb-4h-test`
Test id: `7f55814f-0d8c-4707-b94c-a05efbf2b990`
Test name: `scylla-staging/fruch/longevity-cdc-100gb-4h-test`
Test config file(s):

- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cfc0de5f55f7f615b0093b797848839e7f46d842/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7f55814f-0d8c-4707-b94c-a05efbf2b990`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7f55814f-0d8c-4707-b94c-a05efbf2b990)
- Show all stored logs command: `$ hydra investigate show-logs 7f55814f-0d8c-4707-b94c-a05efbf2b990`

## Logs:
- **db-cluster-7f55814f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/db-cluster-7f55814f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/db-cluster-7f55814f.tar.gz)
- **sct-runner-events-7f55814f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/sct-runner-events-7f55814f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/sct-runner-events-7f55814f.tar.gz)
- **sct-7f55814f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/sct-7f55814f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/sct-7f55814f.log.tar.gz)
- **loader-set-7f55814f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/loader-set-7f55814f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/loader-set-7f55814f.tar.gz)
- **monitor-set-7f55814f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/monitor-set-7f55814f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/monitor-set-7f55814f.tar.gz)
- **parallel-timelines-report-7f55814f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/parallel-timelines-report-7f55814f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7f55814f-0d8c-4707-b94c-a05efbf2b990/20231102_204619/parallel-timelines-report-7f55814f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-cdc-100gb-4h-test/10/)
[Argus](https://argus.scylladb.com/test/f6f63231-9aad-4f89-b1bc-03d3abdd8f87/runs?additionalRuns[]=7f55814f-0d8c-4707-b94c-a05efbf2b990)
</details>

**Comment by roydahan** [comment] 2023-11-05 21:58
@avelanarius please have someone to look at it.
Either the feature doesn't work or we don't understand how to use it / test it.

**Comment by sylwiaszunejko** [comment] 2023-11-10 18:00
@fruch I managed to reproduce the issue, but I have a few questions. Was it also the case in your tests that the correct rack received most of the traffic and only a small amount went to the others? From what I see in the RackAwareRoundRobinPolicy java-driver code, it does not work that only one specific rack receives traffic, but the traffic gets to nodes in local rack first, followed by remote racks in local DC, followed by remote DC. Aren't these results a consequence of this mechanism? Or maybe I misunderstood something. Also for testing I used `cassandra-stress write/read` not `user`, do you know if that could affect the results?

**Comment by fruch** [comment] 2023-11-12 05:43
> @fruch I managed to reproduce the issue, but I have a few questions. Was it also the case in your tests that the correct rack received most of the traffic and only a small amount went to the others? From what I see in the RackAwareRoundRobinPolicy java-driver code, it does not work that only one specific rack receives traffic, but the traffic gets to nodes in local rack first, followed by remote racks in local DC, followed by remote DC. Aren't these results a consequence of this mechanism? Or maybe I misunderstood something. Also for testing I used `cassandra-stress write/read` not `user`, do you know if that could affect the results?

as the graph I've attached (and you can download the monitor data and see it locally), all of the nodes are getting request almost equally, not what you are describing, 

when I was using a multi-dc setup, seemed like all request were going to the target DC

**Comment by sylwiaszunejko** [comment] 2023-11-12 15:22
> as the graph I've attached (and you can download the monitor data and see it locally), all of the nodes are getting request almost equally, not what you are describing,
> 
> when I was using a multi-dc setup, seemed like all request were going to the target DC

I used multi-dc setup previously, with single-dc setup I see the problem clearly. For some reason RackAwareRoundRobinPolicy works fine for me when there are at least two dcs. I will try to find the root cause of such behavior.

**Comment by roydahan** [comment] 2023-11-12 17:58
@fruch in your screenshot, what do the green and the yellow lines represents?
Also, do we expect only the reads to be affected by this policy?

I tried to figure out the expected behavior from our driver [documentation](https://java-driver.docs.scylladb.com/stable/manual/core/load_balancing/#rack-awareness) but it's not that clear....

**Comment by fruch** [comment] 2023-11-12 18:26
> @fruch in your screenshot, what do the green and the yellow lines represents?

2 nodes each one from different AZ

> Also, do we expect only the reads to be affected by this policy?
> 
> I tried to figure out the expected behavior from our driver [documentation](https://java-driver.docs.scylladb.com/stable/manual/core/load_balancing/#rack-awareness) but it's not that clear....

I assume both read and write would behave like the DC aware policy, and would favor the selected AZ as much as possible and fall back to other AZ only if there are no availability nodes in the target AZ.
If there are other considerations, I would assume they should be clear documented/explained

**Comment by mykaul** [comment] 2023-11-12 18:51
Would be useful to catch (network capture) the CQL queries that go to the wrong place.

**Comment by roydahan** [comment] 2023-12-24 11:38
@sylwiaszunejko have you looked into this one?

**Comment by sylwiaszunejko** [comment] 2023-12-27 06:57
@roydahan it will be fixed with this https://github.com/scylladb/scylla-tools-java/pull/367

**Closed as completed** 2024-01-08 15:34 UTC
