### ISSUE TITLE
driver get stuck on failure during refresh node list and token map

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#189] opened 2023-01-03 20:43 UTC
## Issue description
while using sni_proxy, errors during refresh node list and token map, cause cassndra-stress (java-driver) to stuck forever (at least until 2h50m timeout)

impotent to note that at the same time from a different loader pod (on a different host), there an ongoing working stress

from `loader-set-5bd39c6b/sct-loaders-1/cassandra-stress-read-l0-c0-k1-43c3e8b7-2c21-467c-9387-71895f2f3b7c.log`
```
ERROR 13:58:08,308 [Control connection] Unexpected error while refreshing node list and token map
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.TransportException: [a062c85097a0246bab986f5b0748c30a-1219237397.eu-north-1.elb.amazonaws.com:9142:6dde194a-f2a6-4a0e-a515-cfd1ff37a4c4.cql.sct-cluster.sct.scylladb.com] Connection has been closed
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.datastax.driver.core.ControlConnection.refreshNodeListAndTokenMap(ControlConnection.java:778)
	at com.datastax.driver.core.ControlConnection.refreshNodeListAndTokenMap(ControlConnection.java:435)
	at com.datastax.driver.core.Cluster$Manager$NodeListRefreshRequestDeliveryCallback$1.runMayThrow(Cluster.java:3261)
	at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.datastax.driver.core.exceptions.TransportException: [a062c85097a0246bab986f5b0748c30a-1219237397.eu-north-1.elb.amazonaws.com:9142:6dde194a-f2a6-4a0e-a515-cfd1ff37a4c4.cql.sct-cluster.sct.scylladb.com] Connection has been closed
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1737)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1718)
	at com.datastax.driver.core.Connection.defunct(Connection.java:815)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1658)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1648)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at com.datastax.shaded.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at com.datastax.shaded.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at com.datastax.shaded.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1164)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:755)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
	at com.datastax.shaded.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 common frames omitted
com.datastax.driver.core.exceptions.DriverInternalError: An unexpected error happened while sending requests
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

seems like it's reproducible in the job with 2 tenants described below

## Installation details

Kernel Version: 5.4.226-129.415.amzn2.x86_64
Scylla version (or git commit hash): `5.2.0~dev-20230103.63c2cdafe88a` with build-id `50839e9c96279203259fa7675bb4e7b41c765abd`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.0-2-gc6e3b1b
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-multitenant-eks`
Test id: `5bd39c6b-4625-4783-9813-6b78f45d2954`
Test name: `scylla-staging/fruch/longevity-scylla-operator-3h-multitenant-eks`
Test config file(s):

- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a57544468e906614ebe60990c3564cea314081ce/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5bd39c6b-4625-4783-9813-6b78f45d2954`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5bd39c6b-4625-4783-9813-6b78f45d2954)
- Show all stored logs command: `$ hydra investigate show-logs 5bd39c6b-4625-4783-9813-6b78f45d2954`

## Logs:
- **db-cluster-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/db-cluster-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/db-cluster-5bd39c6b.tar.gz)
- **sct-runner-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/sct-runner-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/sct-runner-5bd39c6b.tar.gz)
- **monitor-set-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/monitor-set-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/monitor-set-5bd39c6b.tar.gz)
- **loader-set-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/loader-set-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/loader-set-5bd39c6b.tar.gz)
- **kubernetes-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/kubernetes-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/kubernetes-5bd39c6b.tar.gz)
- **parallel-timelines-report-5bd39c6b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/parallel-timelines-report-5bd39c6b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5bd39c6b-4625-4783-9813-6b78f45d2954/20230103_165947/parallel-timelines-report-5bd39c6b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-3h-multitenant-eks/62/)
</details>

**Comment by fruch** [comment] 2023-01-03 20:47
@avelanarius we need someone to take a look at this one

it's not something I ever remember seeing, sounds related to sni_proxy implementation to me, but can't really put a finger.

**Comment by tnozicka** [comment] 2023-04-21 07:47
Has someone been looking into this?

**Comment by fruch** [comment] 2023-04-21 08:42
> Has someone been looking into this?

@tnozicka have you seen it again ? cause I don't think I've seen such a thing ever since.

**Comment by tnozicka** [comment] 2023-04-21 08:51
I haven't. I am asking from a project planing perspective. We should decide what to do with the issue and whether we need someone to get assigned to it or close it. By your comment the frequency might be low but the impact seems quite bad.

**Comment by avelanarius** [comment] 2023-04-21 09:02
@Bouncheck investigated this issue in the past for a while (I also looked into it). Unfortunately, we haven't been able to reproduce the problem ("cause I don't think I've seen such a thing ever since") or even have a good guess what was causing this problem.

Maybe we should have sent a quick status update comment on this thread, but it would have been "I worked on it for a few days and didn't make much progress"...

**Comment by tnozicka** [comment] 2023-04-21 09:10
No worries and thanks for the update. If you are unable to reproduce it and the reporter hasn't hit it since, should we close it?

**Comment by fruch** [comment] 2023-04-21 10:58
It would serve its purpose as reference also as a closed issue

**Closed as not planned** 2023-04-21 10:57 UTC
Labels: bug
