### ISSUE TITLE
Issue in page Prepared statements

### ISSUE THREAD

**Issue by slivne** [scylladb/java-driver#77] opened 2021-03-14 07:55 UTC
I would like to report an issue in page https://java-driver.docs.scylladb.com/scylla-3.10.2.x/manual/statements/prepared/index

### Problem
The link at the top is broken

https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/PreparedStatement.html

https://java-driver.docs.scylladb.com/latest/manual/statements/prepared/

I think there is an issue with not including version
###  Suggest a fix

**Comment by haaawk** [comment] 2021-03-14 09:53
This must be a problem with docs generation. The links in the repository are correct: https://github.com/scylladb/java-driver/blob/scylla-3.10.2.x/manual/statements/prepared/README.md

**Comment by avelanarius** [comment] 2021-08-31 21:22
Duplicate of #86, which is fixed now.

**Closed as completed by avelanarius** 2021-08-31 21:22 UTC
